<?xml version="1.0" encoding="UTF-8"?>
<project name="gracia_revive_game_registry" default="dist" basedir=".">

    <property name="src.dir" value="src/main/java"/>
    <property name="resources.dir" value="src/main/resources"/>
    <property name="lib.dir" value="lib"/>
    <property name="build.dir" value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="dist.dir" value="dist"/>
    <property name="dist.lib.dir" value="${dist.dir}/lib"/>
    <property name="dist.res.dir" value="${dist.dir}/resources"/>
    <property name="jar.name" value="gracia_revive_game_registry.jar"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <target name="init">
        <mkdir dir="${classes.dir}"/>
        <mkdir dir="${dist.dir}"/>
        <mkdir dir="${dist.lib.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}"
               destdir="${classes.dir}"
               release="21"
    	       encoding="UTF-8"
               includeantruntime="false">

            <classpath>
                <fileset dir="${lib.dir}">
                    <include name="**/*.jar"/>
                </fileset>
            </classpath>

        </javac>
    </target>

    <target name="copy-libs" depends="init">
        <copy todir="${dist.lib.dir}">
            <fileset dir="${lib.dir}">
                <include name="**/*.jar"/>
            </fileset>
        </copy>
    </target>
	
	<target name="copy-runtime-files" depends="init">

	    <copy file="${resources.dir}/startGameRegistry.bat"
	          todir="${dist.dir}" />

	    <copy todir="${dist.dir}/config">
	        <fileset dir="${resources.dir}/config"/>
	    </copy>

	    <copy todir="${dist.dir}/schema">
	        <fileset dir="${resources.dir}/schema"/>
	    </copy>

	</target>
	
    <target name="jar" depends="compile">
        <jar destfile="${dist.dir}/${jar.name}" basedir="${classes.dir}">
        	
            <fileset dir="${resources.dir}">
                <include name="logback.xml"/>
                <include name="servername.json"/>
                <include name="messages_en.properties"/>
                <include name="messages_ro.properties"/>
            </fileset>
        	
            <manifest>
                <attribute name="Main-Class" value="com.graciarevive.registry.bootstrap.RegistryBootstrap"/>
            </manifest>
        </jar>
    </target>

	<target name="dist" depends="clean, compile, jar, copy-libs, copy-runtime-files">
	</target>

</project>